# Generated by Django 5.1.2 on 2024-11-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='to_photo',
            new_name='to_post',
        ),
    ]
