# Generated by Django 5.1.2 on 2024-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_description_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('Advice', 'Advice'), ('Question', 'Question'), ('Story', 'Story'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
