# Generated by Django 5.1.2 on 2024-11-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='git_hub_link',
        ),
    ]
