# Generated by Django 5.1.2 on 2024-11-17 13:24

import ask_a_woman.account.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_git_hub_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='download_i2dvem', max_length=255, null=True, validators=[ask_a_woman.account.validators.validate_and_crop_image, ask_a_woman.account.validators.check_valid_size], verbose_name='image'),
        ),
    ]
